import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import { toast, ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight : ["400", "500", "600", "700"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer theme="dark" />
        {children}
      </body>
    </html>
  );
}
